remove debugger
* about hu.yml translation
it cause error

    YAMLParseError: Nested mappings are not allowed in compact mappings at line 54, column 26:

    descriptionEmptyStore: Amennyiben beleegyezik ebbe a szolgáltatásba, el kell …

just wrapped with single quote to skip the error as I did not understand that language